name: 'Dismiss stale approvals'
description: 'Dismiss approvals on a pull request if the diff has changed'
author: 'Graphite'

inputs:
  github-token:
    description:
      'A GITHUB_TOKEN secret or PAT that has write access to the repository'
    required: true
  fetch-depth:
    default: 50
    description:
      'The maximum length of a branch from head to base that will be compared to the previous run. If the branch is longer than this number, reviews will always be dismissed.'
    required: false


runs:
  using: "composite"
  steps:
    - name: Set Workflow Run URL as Output
      shell: bash
      run: |
        REPO_URL="https://github.com/${{ github.repository }}"
        RUN_URL="$REPO_URL/actions/runs/${{ github.run_id }}"
        echo WORKFLOW_RUN_URL="$RUN_URL" >> $GITHUB_ENV

    - name: Set GitHub path
      shell: bash
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH

    - name: Download SHAs from last run
      shell: bash
      run: |
        latest_artifact.sh "${{ inputs.github-token }}" "${{ github.repository }}" "$(echo ${{github.ref_name}} | cut -d '/' -f 1)" "${{ github.head_ref }}" "${{ github.workflow }}" "dismiss-stale-approvals-shas"
        if [ -f shas.txt ]; then
          echo "PREV_HEAD_SHA=$(head -n 1 shas.txt)" >> $GITHUB_ENV
          echo "PREV_BASE_SHA=$(tail -n 1 shas.txt)" >> $GITHUB_ENV
        fi
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Read SHAs
      shell: bash
      run: |
       echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
       echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

    - name: Check if diff has changed
      shell: bash
      run: |
        if [ -z { env.PREV_HEAD_SHA } ] || [ -z { env.PREV_BASE_SHA } ]; then
          echo ::notice:: "No previous SHAs found; behaving as if diff has changed"
          exit 0
        fi

        git init -q --bare bare.git
        cd bare.git
        git remote add origin https://oauth2:"${{ inputs.github-token }}"@github.com/"${{ github.repository }}".git
        git fetch -q origin --depth="${{ inputs.fetch-depth }}" "${{ env.PREV_HEAD_SHA }}"
        git fetch -q origin --depth="${{ inputs.fetch-depth }}" "${{ env.HEAD_SHA }}"
        RANGE_DIFF=$(git range-diff "${{ env.PREV_BASE_SHA }}".."${{ env.PREV_HEAD_SHA }}" "${{ env.BASE_SHA }}".."${{ env.HEAD_SHA }}")
        HAS_DIFF=$(echo $RANGE_DIFF | awk '{print $3}' | grep -q '^=$'; echo $?)
        echo HAS_DIFF="$HAS_DIFF" >> $GITHUB_ENV
        if [ "$HAS_DIFF" != "0" ]; then
          echo ::notice:: "PR was modified:
          $RANGE_DIFF"
        fi

    - name: Dismiss approvals if diff has changed or if any prior step failed
      if: failure() || env.HAS_DIFF != '0'
      uses: withgraphite/dismiss-all-approvals-js@main
      with:
        github-token: ${{ inputs.github-token }}
        reason: This PR's diff changed since it was approved, so Graphite has dimissed approvals. See the output of `git range-diff` at ${{ env.WORKFLOW_RUN_URL}}

    - name: Write SHAs to file
      shell: bash
      run: |
        echo "${{ env.HEAD_SHA }}" > shas.txt
        echo "${{ env.BASE_SHA }}" >> shas.txt

    - name: Upload SHAs
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: dismiss-stale-approvals-shas
        path: shas.txt
