name: 'Dismiss stale approvals'
description: 'Dismiss approvals on a pull request if the diff has changed'
author: 'Graphite'

inputs:
  github-token:
    description:
      'A GITHUB_TOKEN secret or PAT that has write access to the repository'
    required: true


runs:
  using: "composite"
  steps:
    - name: Download SHAs from last run
      shell: sh
      run: |
        ./latest_artifact.sh "${{ inputs.github-token }}" "${{ github.repository_owner }}" "${{ github.repository }}" "$(echo ${{github.ref_name}} | cut -d '/' -f 1)" "${{ github.workflow }}" "dismiss-stale-approvals-shas"
        ls

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read SHAs
      shell: bash
      run: |
       echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
       echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

    - name: Write SHAs to file
      shell: bash
      run: |
        echo "${{ env.HEAD_SHA }}" > shas.txt
        echo "${{ env.BASE_SHA }}" >> shas.txt

    - name: Upload SHAs
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: dismiss-stale-approvals-shas
        path: shas.txt

    - name: Dismiss approvals
      uses: withgraphite/dismiss-all-approvals-js@main
      with:
        github-token: ${{ inputs.github-token }}
        reason: This PR's diff has changed since it was approved

