name: 'Dismiss stale approvals'
description: 'Dismiss approvals on a pull request if the diff has changed'
author: 'Graphite'

inputs:
  github-token:
    description:
      'A GITHUB_TOKEN secret or PAT that has write access to the repository'
    required: true


runs:
  using: "composite"
  steps:
    - name: Set GitHub path
      shell: bash
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH

    - name: Download SHAs from last run
      shell: bash
      run: |
        latest_artifact.sh "${{ inputs.github-token }}" "${{ github.repository }}" "$(echo ${{github.ref_name}} | cut -d '/' -f 1)" "${{ github.head_ref }}" "${{ github.workflow }}" "dismiss-stale-approvals-shas"
        echo "PREV_HEAD_SHA=$(echo shas.tx | head -n 1)" >> $GITHUB_ENV
        echo "PREV_BASE_SHA=$(echo shas.tx | tail -n 1)" >> $GITHUB_ENV
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read SHAs
      shell: bash
      run: |
       echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
       echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

    - name: Check if diff has changed
      shell: bash
      run: |
        echo "${{ env.HEAD_SHA }}"
        echo "${{ env.BASE_SHA }}"
        echo "${{ env.PREV_HEAD_SHA }}"
        echo "${{ env.PREV_BASE_SHA }}"

    - name: Write SHAs to file
      shell: bash
      run: |
        echo "${{ env.HEAD_SHA }}" > shas.txt
        echo "${{ env.BASE_SHA }}" >> shas.txt

    - name: Upload SHAs
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: dismiss-stale-approvals-shas
        path: shas.txt

    - name: Dismiss approvals
      uses: withgraphite/dismiss-all-approvals-js@main
      with:
        github-token: ${{ inputs.github-token }}
        reason: This PR's diff has changed since it was approved

